apiVersion: v1
kind: Service
metadata:
   name: aks-helloworld
spec:
  selector:
    app: aks-helloworld

  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
  type: LoadBalancer
   ## While running on production cluster, please use 'port: 80'
