trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: "Test"
  inputs:
    targetType: 'inline'
    script: 'mvn test'

- task: Bash@3
  displayName: 'Copy Files'
  inputs:
    targetType: 'inline'
    script: |
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
    
- task: Bash@3
  displayName: 'Publish Artifact: drop'
  inputs:
    targetType: 'inline'
    script: |
       PathtoPublish: '$(build.artifactstagingdirectory)'
      
      